// Copyright (c) 2014-2017 Huasystem Ltd
// BeidouChain code distributed under the GPLv3 license, see COPYING file.

#ifndef BEIDOUCHAINVERSION_H
#define	BEIDOUCHAINVERSION_H

#define BEIDOUCHAIN_VERSION_MAJOR     1
#define BEIDOUCHAIN_VERSION_MINOR     0
#define BEIDOUCHAIN_VERSION_REVISION  0
#define BEIDOUCHAIN_VERSION_STAGE     2
#define BEIDOUCHAIN_VERSION_BUILD     2

#define BEIDOUCHAIN_PROTOCOL_VERSION 10008


#ifndef STRINGIZE
#define STRINGIZE(X) DO_STRINGIZE(X)
#endif

#ifndef DO_STRINGIZE
#define DO_STRINGIZE(X) #X
#endif

#define BEIDOUCHAIN_BUILD_DESC_WITH_SUFFIX(maj, min, rev, build, suffix) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-" DO_STRINGIZE(suffix)

#define BEIDOUCHAIN_BUILD_DESC_FROM_UNKNOWN(maj, min, rev, build) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build)


#define BEIDOUCHAIN_BUILD_DESC "1.0 beta 2"
#define BEIDOUCHAIN_BUILD_DESC_NUMERIC 10000202

#ifndef BEIDOUCHAIN_BUILD_DESC
#ifdef BUILD_SUFFIX
#define BEIDOUCHAIN_BUILD_DESC BEIDOUCHAIN_BUILD_DESC_WITH_SUFFIX(BEIDOUCHAIN_VERSION_MAJOR, BEIDOUCHAIN_VERSION_MINOR, BEIDOUCHAIN_VERSION_REVISION, BEIDOUCHAIN_VERSION_BUILD, BUILD_SUFFIX)
#else
#define BEIDOUCHAIN_BUILD_DESC BEIDOUCHAIN_BUILD_DESC_FROM_UNKNOWN(BEIDOUCHAIN_VERSION_MAJOR, BEIDOUCHAIN_VERSION_MINOR, BEIDOUCHAIN_VERSION_REVISION, BEIDOUCHAIN_VERSION_BUILD)
#endif
#endif

#define BEIDOUCHAIN_FULL_DESC(build, protocol) \
    "build " build " protocol " DO_STRINGIZE(protocol)


#ifndef BEIDOUCHAIN_FULL_VERSION
#define BEIDOUCHAIN_FULL_VERSION BEIDOUCHAIN_FULL_DESC(BEIDOUCHAIN_BUILD_DESC, BEIDOUCHAIN_PROTOCOL_VERSION)
#endif


#endif	/* BEIDOUCHAINVERSION_H */

